backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: "aboutUs"
    label: "About Us"
    folder: "/content/blog/AboutUs"
    create: true
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SubHeader", name: "SubHeader", widget: "string" }
      - { label: "about", name: "about", widget: "text" }
  - name: "aboutUsDonations"
    label: "About Us Donations"
    folder: "/content/blog/AboutUsDonations"
    create: true
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "SubHeader", name: "subHeader", widget: "string" }
      - {
          label: "donationTypes",
          name: "donationTypes",
          widget: "list",
          allow_add: true,
          field:
            { label: "donationType", name: "donationType", widget: "string" },
        }
  - name: "aboutUsMissionVision"
    label: "About Us Mission Vision"
    folder: "/content/blog/AboutUsMissionVision"
    create: true
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "mission", name: "mission", widget: "text" }
      - { label: "vision", name: "vision", widget: "text" }
  - name: "aboutUsPartners"
    label: "About Us Partners"
    folder: "/content/blog/AboutUsPartners"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SubHeader", name: "subHeader", widget: "string" }
      - {
          label: "Partners List",
          name: "partnersList",
          widget: list,
          allow_add: true,
          fields:
            [
              { label: "Partner Name", name: "partnerName", widget: "string" },
              { label: "About", name: "about", widget: "text" },
              { label: "Image", name: "image", widget: "image" },
            ],
        }
  - name: "aboutUsRentals"
    label: "About Us Rentals"
    folder: "/content/blog/AboutUsRentals"
    create: true
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Rental Types",
          name: "rentalTypes",
          widget: "list",
          allow_add: true,
          fields:
            [
              { label: "Header", name: "header", widget: "string" },
              { label: "Content", name: "content", widget: "string" },
            ],
        }
  - name: "meetTheTeam"
    label: "Meet The Team"
    folder: "/content/blog/meetTheTeam"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Team Member",
          name: "teamMember",
          widget: "list",
          allow_add: true,
          fields:
            [
              { label: "Name", name: "names", widget: "string" },
              { label: "Bios", name: "bios", widget: "string" },
              { label: "Email", name: "email", widget: "string" },
              { label: "Image", name: "memberImage", widget: "image" },
            ],
        }
  - name: "FAQ"
    label: "FAQ"
    folder: "/content/blog/FAQ"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Questions",
          name: "questions",
          widget: "list",
          allow_add: true,
          fields:
            [
              { label: "Question", name: "question", widget: "string" },
              { label: "Answer", name: "answer", widget: "text" },
              {
                label: "Answer Image",
                name: "answerImage",
                widget: "image",
                required: false,
              },
            ],
        }
  - name: "HomePage"
    label: "Home Page"
    folder: "/content/blog/HomePage"
    create: true
    fields:
      - { label: "About Us Header", name: "aboutUsHeader", widget: "string" }
      - {
          label: "About Us Content",
          name: "aboutUsHomeContent",
          widget: "list",
          allow_add: true,
          fields:
            [
              {
                label: "Section Title",
                name: "homePageTitle",
                widget: "string",
              },
              {
                label: "Section Content",
                name: "homePageContent",
                widget: "text",
              },
            ],
        }
      - { label: "Resources Title", name: "resourcesTitle", widget: "string" }
      - { label: "Email for CC", name: "mainEmail", widget: "string" }
      - {
          label: "Resources",
          name: "resources",
          widget: "list",
          allow_add: true,
          fields:
            [
              {
                label: "Resource Text",
                name: "resourceText",
                widget: "string",
              },
              {
                label: "Resource Link",
                name: "resourceLink",
                widget: "string",
              },
            ],
        }
  - name: "LandingPage"
    label: "Landing Page"
    folder: "/content/blog/LandingPage/landing-page"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SubHeader", name: "SubHeader", widget: "string" }
      - {
          label: "Landing Page Image",
          name: "landingPageImage",
          widget: "image",
        }
  - name: "hoursMap"
    label: "Hours and Location"
    folder: "/content/blog/hoursMap"
    create: true
    fields:
      - { label: "location", name: "location", widget: "string" }
      - {
          label: "Hours",
          name: "hours",
          widget: "list",
          allow_add: true,
          fields:
            [
              { label: "Day", name: "day", widget: "string" },
              { label: "Times", name: "times", widget: "string" },
            ],
        }
