backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: "aboutUs"
    label: "aboutUs"
    folder: "/content/blog/AboutUs"
    create: true
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SubHeader", name: "SubHeader", widget: "string" }
      - { label: "about", name: "about", widget: "text" }
  - name: "aboutUsDonations"
    label: "aboutUsDonations"
    folder: "/content/blog/AboutUsDonations"
    create: true
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "SubHeader", name: "subHeader", widget: "string" }
      - {
          label: "donationTypes",
          name: "donationTypes",
          widget: "list",
          allow_add: true,
          field:
            { label: "donationType", name: "donationType", widget: "string" },
        }
  - name: "aboutUsMissionVision"
    label: "aboutUsMissionVision"
    folder: "/content/blog/AboutUsMissionVision"
    create: true
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "mission", name: "mission", widget: "text" }
      - { label: "vision", name: "vision", widget: "text" }
  - name: "aboutUsPartners"
    label: "aboutUsPartners"
    folder: "/content/blog/AboutUsPartners"
    create: true
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SubHeader", name: "subHeader", widget: "string" }
      - {
          label: "PartnersList",
          name: "partnersList",
          widget: list,
          allow_add: true,
          fields:
            [
              { label: "PartnerName", name: "partnerName", widget: "string" },
              { label: "About", name: "about", widget: "text" },
              { label: "Image", name: "image", widget: "image" },
            ],
        }
  - name: "aboutUsRentals"
    label: "aboutUsRentals"
    folder: "/content/blog/AboutUsRentals"
    create: true
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "rentalTypes",
          name: "rentalTypes",
          widget: "list",
          allow_add: true,
          fields:
            [
              { label: "header", name: "header", widget: "string" },
              { label: "content", name: "content", widget: "string" },
            ],
        }
  - name: "meetTheTeam"
    label: "MeetTheTeam"
    folder: "/content/blog/meetTheTeam"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "TeamMember",
          name: "teamMember",
          widget: "list",
          allow_add: true,
          fields:
            [
              { label: "name", name: "names", widget: "string" },
              { label: "bios", name: "bios", widget: "string" },
              { label: "email", name: "email", widget: "string" },
              { label: "Image", name: "memberImage", widget: "image" },
            ],
        }
  - name: "FAQ"
    label: "FAQ"
    folder: "/content/blog/FAQ"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Question",
          name: "Question",
          widget: "list",
          allow_add: true,
          fields:
            [
              { label: "Question", name: "names", widget: "string" },
              { label: "answer", name: "answer", widget: "string" },
              { label: "answerImage", name: "answerImage", widget: "image" },
            ],
        }
  - name: "LandingPage"
    label: "LandingPage"
    folder: "/content/blog/LandingPage/landing-page"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SubHeader", name: "SubHeader", widget: "string" }
      - { label: "LandingPageimage", name: "landingPageimage", widget: "image" }
